# Generated by Django 2.2.16 on 2020-10-20 08:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0044_codeassignmentnudgeemailtemplates'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferAssignmentEmailSentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('enterprise_customer', models.UUIDField(help_text='UUID for an EnterpriseCustomer from the Enterprise Service.')),
                ('email_type', models.CharField(choices=[('assign', 'Assign'), ('remind', 'Remind'), ('revoke', 'Revoke')], max_length=32)),
                ('template', models.ForeignKey(blank=True, help_text='The ID of the template used to send email.', null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.OfferAssignmentEmailTemplates')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
